# Generated by Django 4.2.7 on 2026-03-05 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_room_review_note_room_reviewed_at_room_reviewed_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='room',
            name='deposit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
