# Generated by Django 4.2.13 on 2026-04-01 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_room_address_room_deposit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='owner_contact',
            field=models.CharField(max_length=255),
        ),
    ]
