# Generated by Django 4.2.13 on 2026-04-01 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_owner_contact_max_length'),
    ]

    operations = [
        # views field already added by 0005_room_views — no-op to avoid duplicate column
    ]
