# Generated by Django 4.2.7 on 2026-04-12 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_room_views'),
        ('rooms', '0006_add_views_field'),
    ]

    operations = [
    ]
