# Generated by Django 4.2.7 on 2026-04-22 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0012_room_owner_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('NEEDS_CHANGES', 'Needs Changes'), ('SUSPENDED', 'Suspended')], default='APPROVED', max_length=20),
        ),
        migrations.AlterField(
            model_name='room',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
