# Generated by Django 4.2.7 on 2026-03-05 02:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('delivery', '0002_alter_delivery_status_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverypartner',
            name='review_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverypartner',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverypartner',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_delivery_partners', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliverypartner',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('NEEDS_CHANGES', 'Needs Changes'), ('SUSPENDED', 'Suspended')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_user_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
