# Generated by Django 4.2.7 on 2026-03-05 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_deliverypartner_review_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverypartner',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='deliverypartner',
            name='vehicle_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='deliverypartner',
            name='vehicle_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
