// src/styles/studentTheme.js
export const STUDENT_THEME = {
  navy: "#1f4f96",
  navy2: "#2c66b8",
  sky: "#5aa9ff",
  bg: "#eef3ff",
  card: "rgba(255,255,255,0.86)",
  cardSolid: "#ffffff",
  text: "#0f172a",
  muted: "#5b6b8a",
  border: "rgba(15, 23, 42, 0.10)",
  shadow: "0 12px 34px rgba(20, 45, 90, 0.14)",
  pill: "rgba(31, 79, 150, 0.10)",
};

export const STUDENT_LAYOUT = {
  page: {
    minHeight: "100vh",
    background: `radial-gradient(900px 500px at 20% 10%, rgba(90,169,255,0.25), transparent 60%),
                 radial-gradient(900px 500px at 85% 45%, rgba(31,79,150,0.18), transparent 60%),
                 ${STUDENT_THEME.bg}`,
    padding: "18px 18px 40px",
  },
  container: {
    maxWidth: 1200,
    margin: "0 auto",
  },
  card: {
    background: STUDENT_THEME.card,
    border: `1px solid ${STUDENT_THEME.border}`,
    borderRadius: 16,
    boxShadow: STUDENT_THEME.shadow,
    padding: 14,
    backdropFilter: "blur(8px)",
  },
  cardSolid: {
    background: STUDENT_THEME.cardSolid,
    border: `1px solid ${STUDENT_THEME.border}`,
    borderRadius: 16,
    boxShadow: STUDENT_THEME.shadow,
    padding: 14,
  },
  cardHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    marginBottom: 12,
  },
  cardTitle: {
    fontSize: 15,
    fontWeight: 900,
    color: STUDENT_THEME.text,
  },
  cardLink: {
    fontSize: 13,
    fontWeight: 900,
    color: STUDENT_THEME.navy,
    textDecoration: "none",
  },
  pill: {
    fontSize: 11,
    fontWeight: 900,
    padding: "4px 10px",
    borderRadius: 999,
    background: STUDENT_THEME.pill,
    color: STUDENT_THEME.navy,
    border: `1px solid ${STUDENT_THEME.border}`,
  },
  input: {
    height: 40,
    borderRadius: 12,
    border: `1px solid ${STUDENT_THEME.border}`,
    padding: "0 12px",
    fontWeight: 800,
    color: STUDENT_THEME.text,
    background: STUDENT_THEME.cardSolid,
    outline: "none",
    width: "100%",
    boxSizing: "border-box",
  },
  textarea: {
    width: "100%",
    padding: "0.75rem",
    border: `1px solid ${STUDENT_THEME.border}`,
    borderRadius: 12,
    minHeight: 110,
    marginTop: "0.5rem",
    boxSizing: "border-box",
    background: STUDENT_THEME.cardSolid,
    outline: "none",
    fontWeight: 700,
    color: STUDENT_THEME.text,
  },
  primaryBtn: {
    height: 40,
    borderRadius: 999,
    border: "none",
    cursor: "pointer",
    padding: "0 18px",
    fontWeight: 900,
    color: "#fff",
    background: `linear-gradient(90deg, ${STUDENT_THEME.navy}, ${STUDENT_THEME.sky})`,
    boxShadow: "0 10px 24px rgba(31, 79, 150, 0.25)",
    textDecoration: "none",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    whiteSpace: "nowrap",
  },
  outlineBtn: {
    height: 40,
    borderRadius: 999,
    cursor: "pointer",
    padding: "0 18px",
    fontWeight: 900,
    color: STUDENT_THEME.navy,
    background: "rgba(255,255,255,0.85)",
    border: `1px solid ${STUDENT_THEME.border}`,
    textDecoration: "none",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    whiteSpace: "nowrap",
  },
};