# Generated by Django 4.2.7 on 2026-04-22 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_restaurant_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='food_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='meal_type',
            field=models.CharField(blank=True, choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='veg_nonveg',
            field=models.CharField(blank=True, choices=[('veg', 'Vege'), ('nonveg', 'Non-Vege')], max_length=10, null=True),
        ),
    ]
