# Generated by Django 4.2.7 on 2026-04-22 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_add_food_id_meal_type_veg_nonveg'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='meal_type',
            field=models.CharField(blank=True, choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='veg_nonveg',
            field=models.CharField(blank=True, choices=[('Veg', 'Veg'), ('NonVeg', 'NonVeg')], max_length=10, null=True),
        ),
    ]
