# Generated by Django 4.2.7 on 2026-04-14 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('notification_type', models.CharField(choices=[('new_owner', 'New Owner Registration'), ('new_student', 'New Student Registration'), ('new_restaurant_owner', 'New Restaurant Owner'), ('new_delivery_partner', 'New Delivery Partner'), ('pending_room', 'Pending Room Approval'), ('pending_restaurant', 'Pending Restaurant Approval'), ('pending_partner', 'Pending Partner Approval'), ('new_report', 'New Report Submitted'), ('new_booking', 'New Booking'), ('new_order', 'New Order'), ('general', 'General')], default='general', max_length=30)),
                ('is_read', models.BooleanField(default=False)),
                ('target_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
