# Generated by Django 4.2.7 on 2026-02-24 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_student',
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student'), ('hostel_owner', 'Hostel Owner'), ('restaurant_owner', 'Restaurant Owner'), ('delivery_partner', 'Delivery Partner'), ('admin', 'Admin')], default='student', max_length=20),
        ),
    ]
