# Generated by Django 4.2.7 on 2026-04-12 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_studentprofile_latitude_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostelownerprofile',
            name='is_under_verification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hostelownerprofile',
            name='verification_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='OwnerVerificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nic_passport_number', models.CharField(blank=True, max_length=100)),
                ('address_proof', models.TextField(blank=True)),
                ('business_reg_no', models.CharField(blank=True, max_length=100)),
                ('nic_doc', models.FileField(blank=True, null=True, upload_to='verification_docs/')),
                ('address_doc', models.FileField(blank=True, null=True, upload_to='verification_docs/')),
                ('business_doc', models.FileField(blank=True, null=True, upload_to='verification_docs/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_note', models.TextField(blank=True, default='')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification_request', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
